### ISSUE TITLE
Doubt on cache

### ISSUE THREAD

**Issue by kalyangvs** [randyzwitch/streamlit-embedcode#8]
Hi,
Can the code be cached?
For example, if there is a widget (selectbox) and its state changes, can the code be avoided to fetch again via caching.
st.cache() does not work with this.

**Comment by randyzwitch** [comment]
Hi @gvskalyan, it seems like it should work. What code are you running?

**Comment by kalyangvs** [comment]
Please find the snippet:

```python
import streamlit as st
from streamlit_embedcode import github_gist, gitlab_snippet

option = st.sidebar.radio('test',["agree", 'disagree'])
if option=="agree":
    github_gist("https://gist.github.com/randyzwitch/be8c5e9fb5b8e7b046afebcac12e5087/")
else:
    gitlab_snippet("https://gitlab.com/snippets/1995463")
```
My doubt is, does while I keep altering radio button value will it (streamlit) fetch the gist continuously from the server and is there an option/hack to ask the browser to cache the particular component. (Does st's state  help here?)
Thanks.

**Comment by randyzwitch** [comment]
I see. I think there are a few things here...

Technically, this could be cached. `st.cache()` works by caching the return value of a function, based on the inputs. So something like this would work:

```python

@st.cache()
def github():
    return github_gist("https://gist.github.com/randyzwitch/be8c5e9fb5b8e7b046afebcac12e5087/")

@st.cache()
def gitlab():
    return gitlab_snippet("https://gitlab.com/snippets/1995463")

import streamlit as st
from streamlit_embedcode import github_gist, gitlab_snippet

option = st.sidebar.radio('test',["agree", 'disagree'])
if option=="agree":
    github()
else:
    gitlab()
```

Because `github()` and `gitlab()` don't have any arguments, they will be cached the first time this is run, then remain in cache for the rest of the app lifetime (unless they are purged by something else). From a practical perspective, this might not do much. The cached portion will represent the Streamlit HTML for these functions (which are pretty tiny), but that HTML contains the JavaScript snippet from GitHub/Gitlab. So in that sense, it will always be pinging GitHub/Gitlab for the result, because that's how their embedding snippets work.

**Comment by kalyangvs** [comment]
yes, but when they remain in cache they should be accessible throughout the session.
In the above example only for the first time they are written and disappear later!
Is this intended behaviour?

**Comment by randyzwitch** [comment]
I don't understand your question. What behavior are you expecting? The cache is a reference to whether the data is stored in RAM or recalculated on each app refresh.

**Comment by kalyangvs** [comment]
Please find the images attached.

* When the App is loaded. Since the default is agree it prints github_gist (Using the same snippet)
![image](https://user-images.githubusercontent.com/42022935/88260282-b3888d00-cce1-11ea-800c-94c06ba3d538.png)
* When `disagree` is selected after loading implies gitlab_snippet.
![image](https://user-images.githubusercontent.com/42022935/88260449-03ffea80-cce2-11ea-8d24-c54cb423b01d.png)
* After the above two, when agree is selected or disagree is selected, none of the content is re-shown.
![image](https://user-images.githubusercontent.com/42022935/88260567-44f7ff00-cce2-11ea-856e-4e6a3b748788.png)
![image](https://user-images.githubusercontent.com/42022935/88260586-4de8d080-cce2-11ea-8886-3164e161bcfb.png)

Intended behaviour - The content should be displayed how many ever times we select the options.

**Comment by randyzwitch** [comment]
Got it. The app actually throws a warning on startup:

![image](https://user-images.githubusercontent.com/2762787/88302375-c8f6ba80-ccd3-11ea-94ff-c023d68fb1d8.png)

So removing the `@st.cache` calls makes the app work as expected.  This is what I was trying to highlight here https://github.com/randyzwitch/streamlit-embedcode/issues/8#issuecomment-662425696 , but didn't do so well. From a performance standpoint, I don't think any of them would've needed caching anyway, but I'll think about how to put a note in the docs to not use the cache decorator.
